[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
* {{ commit.message | upper_first | trim }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
commit_parsers = [
  { message = "^[Ff]ix", group = "Bug Fixes" },
  { message = "^[Aa]dd|^[Nn]ew|^[Ff]eat", group = "Features" },
  { message = "^[Rr]efactor", group = "Refactor" },
  { message = "^[Uu]pdate|^[Ii]mprove", group = "Improvements" },
  { message = ".*", group = "Changes" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
